### DISCUSSION TITLE
Adapter factory should allow/use user provided customized adapter class

### DISCUSSION THREAD

**Discussion by ismailsimsek** [dbt-labs/dbt-adapters#259] [Ideas]
Currently in-order to use custom adapter user needs to create whole new adapter and duplicate a lot of code. 

ideally [dbt factory code](https://github.com/dbt-labs/dbt-adapters/blob/7e9731cd819d521ffd638f0e1b96a96e58504eb5/dbt/adapters/factory.py#L62) should allow using user provided Adapter class, by providing custom adapter class name

Example config with custom adapter

```
snowflake:
  target: test
  outputs:
    test:
      type: snowflake
      adapter: my.python.library.SnowflakeAdapterV2Customized
```

```python
class SnowflakeAdapterV2Customized(SnowflakeAdapter):
    @available
    def my_custom_method(self, parsed_model: Dict, compiled_code: str):
        print('CUSTOM adapter method, available to jinja')

# FIX this part should be done by dbt AdapterContainer, Factory class!!
# FIX patch new adapter. this is workaround to replace current adapter class!
dbt.adapters.snowflake.Plugin = AdapterPlugin(
    adapter=SnowflakeAdapterV2Customized, credentials=SnowflakeCredentials, include_path=snowflake.PACKAGE_PATH  # type: ignore
)

# run dbt, now it uses new adapter class
dbt = DbtCliRunner()
result: dbtRunnerResult = dbt.invoke(args)
```
