### DISCUSSION TITLE
ICEBERG_FILESYSTEM_ERROR on table materialization

### DISCUSSION THREAD

**Discussion by JanKrl** [dbt-labs/dbt-adapters#925] [Q&A]
Hi,
I am transitioning my project from dbt-glue to dbt-athena. I use iceberg tables in AWS.

I configured the following target in my `proiles.yaml`:
```yaml
    athena:
      type: athena
      s3_staging_dir: s3://<athena_output_bucket>/
      s3_data_dir: s3://<data_bucket>/
      region_name: <region>
      schema: <schema>
      database: awsdatacatalog
      work_group: <work_group>
      aws_access_key_id: <access_key>
      aws_secret_access_key: <secret_key>
      threads: 1
```
 and my dbt_project.yaml
```yaml
models:
  dbt_model:
    +table_type: iceberg
    +format: parquet
    +s3_data_naming: schema_table_unique
    raw:
      +schema: stage
      +materialized: table
```

I created a simple model to verify the configuration.

```sql
select
    date_time,
    json_extract_scalar(message, '$.id') as message_type,
    message
from
    {{ source("ingress", "ingress_sample") }} LIMIT 100
```

When I run the model the following happens:
1. It takes a couple of seconds to run
2. Terminal prints the following error `ICEBERG_FILESYSTEM_ERROR: Cannot create a table on a non-empty location: s3://<data_bucket>/<schema>/<model_name>/e563b5ca-acd4-4924-ac79-e48cf5d600e4. You may need to manually clean the data at location 's3://<athena_output_bucket>/tables/ee6f7919-083f-4036-96f5-3ed6e498ffd3' before retrying. Athena will not delete data in your account.`
3. I can see files in `s3://<data_bucket>/<schema>/<model_name>/`
4. `s3://<athena_output_bucket>/` is empty
5. The table doesn't show up in glue catalog.

Any ideas where the problem lies?
