### ISSUE TITLE
[Bug] Adding a INFORMATION_SCHEMA source for BigQuery makes all catalog calls to use that source definition

### ISSUE THREAD

**Issue by rloredo** [dbt-labs/dbt-adapters#1005]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If I create a source file
```yaml
version: 2

sources:
  - name: information_schema
    schema: region-europe-west4.INFORMATION_SCHEMA
    tables:
      - name: column_field_paths
        identifier: COLUMN_FIELD_PATHS
```

And run `dbt docs generate` I get the error

```
Encountered an error while generating catalog: Database Error
  Invalid project ID 'my-project-id.region-europe-west4'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
```

### Expected Behavior

It shouldn't use that defined source, and there should be a way of referencing information schema tables with `source()` macro that doesn't collide with the catalog generation.

### Steps To Reproduce

Add a source file 
```yaml
version: 2

sources:
  - name: information_schema
    schema: region-europe-west4.INFORMATION_SCHEMA
    tables:
      - name: column_field_paths
        identifier: COLUMN_FIELD_PATHS
```

run `dbt docs generate`

### Relevant log output

```shell

```

### Environment

```markdown
- OS: MacOS, Ubuntu 24
- Python: ">=3.10,<3.11"
- dbt-bigquery = ">=1.8.0,<1.8.1"
- dbt-core = ">=1.8.0,<1.8.1"
```

### Which database adapter are you using with dbt?

bigquery

**Comment by amychen1776** [comment]
Thanks @dbeatty10 !

@rloredo I would love to better understand why you're using the information schema as a source. Would you be open to sharing your use case?

**Comment by rloredo** [comment]
Hi @amychen1776 we use it to build models of the metadata for auditing and governance. For example, using COLUMN_FIELD_PATHS we get all the tables columns and we use that information for PII checks, enrich observability data, etc.


However, I don't know why it's relevant how I use a source. It's a source that is available, that can be defined as any other source, and the only difference is that dbt calls it too. From what I understood, dbt overrides how it's called because there's no real separation between the source macro and the other components. Imo the solution won't come from a way for users to use this source, but from fixing the modularization of how is it used by dbt processes vs. user source macro.

**Comment by amychen1776** [comment]
Hi @rloredo ! Thank you for the context. Use cases help us better navigate what is the broader thing you are trying to accomplish so we can have a full picture on how we might be able to troubleshoot. It's also important because with 1.10 and onward, we are looking into things like typed macros and protected macros so that there's a standard expectation of what is supported (this also helps us in the development process to ensure we aren't breaking projects unintendedly).

**Comment by colin-rogers-dbt** [comment]
@rloredo 

Does this behavior persist if the source name is different?
i.e. 
```
version: 2

sources:
  - name: information_schema_src
    schema: region-europe-west4.INFORMATION_SCHEMA
    tables:
      - name: column_field_paths
        identifier: COLUMN_FIELD_PATHS
```
