### ISSUE TITLE
[Bug] Deadlock on Postgres when creating foreign keys

### ISSUE THREAD

**Issue by georgek** [dbt-labs/dbt-adapters#1021]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using foreign keys constraints on Postgres it is possible to get into a deadlock when running multiple threads.

This happens because creating a foreign key (either via `CREATE TABLE` or `ALTER TABLE`) acquires a `ShareRowExclusiveLock` lock on the table being referenced. So if several tables reference the same set of tables (for example, several fact tables referencing the same dimensions) then eventually you'll hit a deadlock.

### Expected Behavior

dbt is aware of the possibility of deadlock and doesn't materialise two tables that reference at least two of the same tables at the same time.

### Steps To Reproduce

It is difficult to reproduce reliably, but I got the following minimal example to produce a deadlock one time.

models.yaml
```yaml
models:
  - name: parent1

    config:
      contract:
        enforced: true

    columns:
      - name: col
        data_type: integer
        constraints:
          - type: primary_key

  - name: parent2

    config:
      contract:
        enforced: true

    columns:
      - name: col
        data_type: integer
        constraints:
          - type: primary_key

  - name: child1

    config:
      contract:
        enforced: true

    columns:
      - name: col1
        data_type: integer
        constraints:
          - type: foreign_key
            to: ref('parent1')
            to_columns: [col]

      - name: col2
        data_type: integer
        constraints:
          - type: foreign_key
            to: ref('parent2')
            to_columns: [col]

  - name: child2

    config:
      contract:
        enforced: true

    columns:
      - name: col2
        data_type: integer
        constraints:
          - type: foreign_key
            to: ref('parent2')
            to_columns: [col]

      - name: col1
        data_type: integer
        constraints:
          - type: foreign_key
            to: ref('parent1')
            to_columns: [col]
```

parent1.sql

```sql
SELECT generate_series(1, 1000000) AS col
```

parent2.sql

```sql
SELECT generate_series(1, 1000000) AS col
```

child1.sql

```sql
SELECT generate_series(1, 1000000) AS col1, generate_series(1, 1000000) AS col2
```

child2.sql

```sql
SELECT generate_series(1, 1000000) AS col1, generate_series(1, 1000000) AS col2
```

### Relevant log output

```shell
deadlock detected
Process 1183612 waits for ShareRowExclusiveLock on relation 89662846 of database 17303 ; blocked by process 1183616.
Process 1183616 waits for ShareRowExclusiveLock on relation 89663224 of database 17303 ; blocked by process 1183612.
```

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: 3.13
- dbt: 1.9.3
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

I've tried changing the order of the columns and/or constraints but have been unable to conclude if this makes a difference. I am getting this error in production every few days and the conflicting tables do have the constraints specified in a different order. This would make sense if Postgres acquires the locks in the same order as they are specific in the SQL, but I'm unable to find any documentation on this. If this is true it might be possible for dbt to order the columns to avoid the possibility of deadlock.
