### ISSUE TITLE
[Bug] Scope not respected with `impersonate_service_account` (method: oauth; scope: drive.readonly)

### ISSUE THREAD

**Issue by qzdl** [dbt-labs/dbt-adapters#1106]
### Is this a new bug?

- [x] I believe this is a new bug
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Which packages are affected?

- [ ] dbt-adapters
- [ ] dbt-tests-adapter
- [ ] dbt-athena
- [ ] dbt-athena-community
- [x] dbt-bigquery
- [ ] dbt-postgres
- [ ] dbt-redshift
- [ ] dbt-snowflake
- [ ] dbt-spark

### Current Behavior

With two profiles (`test`, `prod`) which are both able to execute jobs against arbitrary objects based on bigquery-storage tables -- only the profile using `impersonate_service_account` fails for those objects based on google-drive.

### Expected Behavior

One would expect both profiles to execute SELECT jobs against the drive-based objects without error.

## Given
- `python=3.11.11 dbt-core==1.8.8 dbt-bigquery==1.8.3`
- `Application Default Credentials` generated via:
  ```
  gcloud auth application-default login  \
        --scopes='https://www.googleapis.com/auth/drive.readonly,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/bigquery'
  ```
- Profile (`test`) which is able execute the given queries:
  ```
    test:
      dataset: d
      execution_project: ep
      location: US
      method: oauth
      project: p
      threads: 32
      type: bigquery
  ```
- Profile (`prod`) which is unable execute the given queries (see error below):
  ```
    prod:
      dataset: d
      execution_project: ep
      location: US
      method: oauth
      impersonate_service_account: sa@p.iam.gserviceaccount
      project: p
      threads: 32
      type: bigquery
  ```
- A google-sheet, (`my_sheet`) which is shared with my actual user & `sa@p.iam.gserviceaccount` (which perhaps incidentally, originates from an entirely distinct google-org).
- A `sources.yml` referencing the remote-table
  ```
  - name: sheets
    database: d
    schema: sheets
    tables:
      - name: my_sheet
  ```
- A model `models/gd/my-sheet.sql` which references the sheet:
  ```
  select a, b, c from {{ source('sheets', 'my_sheet') }}
  ```
- A configuration `models/gd/schema.yml`:
  ```
  version: 2

  models:
    - name: my-sheet
      data_tests:
        - unique:
            column_name: 'concat(a, b, c)'
  ```

-----

## When
- Running any command from the concerned profile, which performs  upon the drive-based object
  - i.e. Creation of view succeeds -- Tests fail with error:
    ```
    dbt build --target prod -s my-sheet
    ```

-----

## Then
- An Error is returned from GCP, relating to scopes:
  ```
  Access Denied: BigQuery BigQuery: Permission denied while getting Drive credentials.
  ```

### Relevant log output

```shell

```

### Environment

```markdown
- OS: GNU/Linux (GNU Guix)
- Python: 3.11.11
- dbt-adapters:
  - dbt-bigquery==1.8.3
```

### Additional Context

I have read all issues pertaining to Scopes & Impersonation, from `dbt-labs/dbt-core` and this repo, but have not found a report which matches these circumstances.

I have attempted to bake the scopes into the given ClientID of the Service Account, as per "Domain Wide Delegation" with the given scope `https://www.googleapis.com/auth/drive.readonly`
- In google-org as "super-admin", See <https://admin.google.com/ac/owl/domainwidedelegation>
- From documentation, See <https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority>
  -  Note that this is likely a fool's errand, as leveraging DWD requires extra code which is not contained in your library, and the specification of a user from the given google-org (... inappropriate permission model).

When removing the impersonation from `profile: prod`, all SELECT commands work flawlessly.

I have attempted to use an alternative ADC, with `--impersonate-service-account ... --scopes ...`, which results in the same error.

Any comment / reproduction is appreciated
