### ISSUE TITLE
[Bug] Order matters if ref table & source table have same name

### ISSUE THREAD

**Issue by ajitjunghare-johnlewis** [dbt-labs/dbt-adapters#1136]
### Is this a new bug?

- [x] I believe this is a new bug
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Which packages are affected?

- [ ] dbt-adapters
- [x] dbt-tests-adapter
- [ ] dbt-athena
- [ ] dbt-athena-community
- [ ] dbt-bigquery
- [ ] dbt-postgres
- [ ] dbt-redshift
- [ ] dbt-snowflake
- [ ] dbt-spark

### Current Behavior

```
unit_tests:
  - name: test_non_heritage_data
    model: vw_ledger
    given:
      - input: source('XYZ_heritage', 'fact_ledger')
        rows: []
      - input: ref('fact_ledger')
        rows:
          - TRAN_DATE: '2024-12-30'
            POST_DATE: '2024-12-30'
            ITEM: 'A'
            LOAD_TIMESTAMP: '2024-12-30 00:00:00'
      - input: source('this', 'cut_off_date')
        rows:
          - value: '2024-12-29'
    expect:
          format: sql
          rows: |
            SELECT '2024-12-30' AS TRAN_DATE,
                   '2024-12-30' AS POST_DATE,
                   'A' AS ITEM
```
For test like above, if I change the order of inputs & put input: source('XYZ', 'fact_stock_ledger'), at the end.  The `__dbt__cte__fact_ledger` has `limit 0` at the end. It means, the generated tests code, doesnt segregate tests data with respect to ref & source, only keeps data as per table name.

### Expected Behavior

The order of input shouldnt matter, even if ref & source has same table name. 

both of the below tests should pass
```
unit_tests:
  - name: test_non_heritage_data
    model: vw_ledger
    given:
      - input: source('XYZ_heritage', 'fact_ledger')
        rows: []
      - input: ref('fact_ledger')
        rows:
          - TRAN_DATE: '2024-12-30'
            POST_DATE: '2024-12-30'
            ITEM: 'A'
            LOAD_TIMESTAMP: '2024-12-30 00:00:00'
      - input: source('this', 'cut_off_date')
        rows:
          - value: '2024-12-29'
    expect:
          format: sql
          rows: |
            SELECT '2024-12-30' AS TRAN_DATE,
                   '2024-12-30' AS POST_DATE,
                   'A' AS ITEM
```

```
unit_tests:
  - name: test_non_heritage_data
    model: vw_ledger
    given:
      - input: ref('fact_ledger')
        rows:
          - TRAN_DATE: '2024-12-30'
            POST_DATE: '2024-12-30'
            ITEM: 'A'
            LOAD_TIMESTAMP: '2024-12-30 00:00:00'
      - input: source('XYZ_heritage', 'fact_ledger')
        rows: []
      - input: source('this', 'cut_off_date')
        rows:
          - value: '2024-12-29'
    expect:
          format: sql
          rows: |
            SELECT '2024-12-30' AS TRAN_DATE,
                   '2024-12-30' AS POST_DATE,
                   'A' AS ITEM
```

### Steps To Reproduce

1. in my example I have a model create which I refer as ref('fact_ledger'), I have another table in different schema as source but has same name, I refer it as source('diff_schema', 'fact_ledger')
2.create a model having union between two separate tables having same name . 
example
```select *,'X' as source from {{ref('fact_ledger')}}
union all
select *, 'Y' as source from {{source ('diff_schema', 'fact_ledger')}}```
3.Create a Unit tests, and make one of the table empty. 
3.1 execute the test, if test passes reverse the order of inputs & test again.


### Relevant log output

```shell

```

### Environment

```markdown
- OS:Mac OS Sonoma 14.7.2
- Python:3.12
- dbt-adapters:
- <adapter>:
```
