### ISSUE TITLE
[Bug] hard_deletes: new_record causes invalid identifier error when a new column is added to the source table

### ISSUE THREAD

**Issue by Kiyoshi09** [dbt-labs/dbt-adapters#1138]
### Is this a new bug?

- [x] I believe this is a new bug
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Which packages are affected?

- [ ] dbt-adapters
- [ ] dbt-tests-adapter
- [ ] dbt-athena
- [ ] dbt-athena-community
- [ ] dbt-bigquery
- [ ] dbt-postgres
- [ ] dbt-redshift
- [x] dbt-snowflake
- [ ] dbt-spark

### Current Behavior

When the `hard_deletes: new_record` property is enabled in a snapshot configuration, and a new column is added to the source table, running `dbt snapshot` results in a SQL compilation error:

```
000904 (42000): SQL compilation error: error line XXX at position YY
  invalid identifier 'NEWLY_ADDED_COLUMN'
```

This appears to happen because dbt references the newly added column in the **deletion_records** CTE when creating the temporary table (__dbt_tmp). However, the snapshot table does not yet include the new column, causing the query to fail.

### Expected Behavior

After adding a new column to the source table, dbt snapshot should not fail. The snapshot process should be able to handle the schema difference, and `hard_deletes: new_record` should still work correctly even if the snapshot table does not yet include the new column.

### Steps To Reproduce

1. Configure a snapshot with `hard_deletes: new_record`. Example:
```
snapshots:
  - name: snapshot1
    relation: <source>
    config:
      unique_key: id
      strategy: check
      check_cols: all
      dbt_valid_to_current: "to_date('9999-12-31')"
      hard_deletes: new_record
```

2. Run `dbt snapshot` to create the initial snapshot table.
3. Add a new column to the source table
4. Run `dbt snapshot` again.
5. Observe the following error:
```
000904 (42000): SQL compilation error: error line XXX at position YY
  invalid identifier 'NEWLY_ADDED_COLUMN'
```

### Relevant log output

```shell

```

### Environment

```markdown
I’ve confirmed this behavior with Snowflake, but I haven’t tested it with other databases
```
