### ISSUE TITLE
[Bug] Unit tests fail when input has a column name with a quoted identifier

### ISSUE THREAD

**Issue by mpatek** [dbt-labs/dbt-adapters#205]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In BigQuery:

Supposing an input table with a reserved-word-named column like:

```
-- stg
SELECT id, loaded_at, `from` FROM {{ source('some', source') }}
```

And a downstream table like:

```
-- some_model
SELECT id, loaded_at FROM {{ ref('stg') }}
qualify row_number() over (partition by id order by loaded_at desc) = 1
```

And a unit test like:
```
version: 2

unit_tests:
  - name: test__some_model
    model: some_model
    given:
      - input: ref('stg')
        rows:
          - {id: "a", loaded_at: "2024-01-01"}
          - {id: "a", loaded_at: "2024-01-02"}
          - {id: "a", loaded_at: "2024-01-02"}
    expect:
      rows:
        - {id: "a", loaded_at: "2024-01-02"}
```

If I try `dbt test --select test_type:unit`

I get: `Syntax error: Unexpected keyword FROM`

### Expected Behavior

Expect tests to pass without errors.

### Steps To Reproduce

1. Create input model with keyword-named column (e.g. `from`)
2. Create output model that selects from the input model (not necessarily including the reserved-word-named column).
3. Add unit test that puts data into input model and runs expectations on output model
4. Run unit test

### Environment

```markdown
- OS: macOS Monterey
- Python: 3.11.7
- dbt-adapter: 1.1.0
```

### Additional Context

Original Issue opened in the dbt-core repo: https://github.com/dbt-labs/dbt-core/issues/10112

**Comment by jtcohen6** [comment]
Thanks for reopening here @mpatek!

Prototype of potential solution:
- #202

**Comment by dbeatty10** [comment]
See below for a minimal reproducible example that covers the maximal number of edge cases.

<details>
<summary>

### Minimal reprex
</summary>

`models/my_model.sql`

```sql
select 1 as {{ adapter.quote("from") }}
```

`models/_unit.yml`

```yaml
unit_tests:

  - name: test___my___model
    model: my_model
    given: []
    expect:
      rows:
        - {from: 1}
```

Run the model and its tests:
```shell
dbt build -s my_model
```

</details>
