### ISSUE TITLE
[Bug] Can't use data contract constraints together with 'time_ingestion_partitioning="true"' in incremental models

### ISSUE THREAD

**Issue by LennartKloppenburg** [dbt-labs/dbt-adapters#525]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Dbt errors when combining an incremental model with `time_ingestion_partitioning` enabled and also enforcing model contract constraints.

I'd love to know whether this is intended or if this is potentially a bug that could be worked on :)

### Expected Behavior

Dbt should not error out on columns 'consumed' by the `time_ingestion_partitioning` flags that are in the dbt model but not factually in the output schema or BigQuery table when enforcing [model contract constraints](https://docs.getdbt.com/reference/resource-properties/constraints#platform-specific-support).

The partitioning column should not have 'presence enforcement' when this flag is enabled (ideally).

### Steps To Reproduce

```
# incremental_test.sql
{{ config(
    materialized="incremental",
    on_schema_change="fail",
    partition_by={
      "field": "created_date",
      "data_type": "timestamp",
      "granularity": "day",
      "time_ingestion_partitioning": true,
    }
) }}

SELECT
  'A' AS letter,
  1 AS digit,
  CURRENT_DATE() AS created_date
```
When enforcing the data contract like so:

```
# incremental_test.yaml
models:
  - name: incremental_test
    config:
      contract:
        enforced: true
    columns:
      - name: letter
        data_type: STRING
        constraints:
          - type: not_null
      - name: digit
        data_type: INTEGER
        constraints:
          - type: not_null
```

and subsequently building with `dbt build --select incremental_test` I get the error attached in the log output.

### Relevant log output

```shell
This model has an enforced contract that failed.
  Please ensure the name, data_type, and number of columns in your contract match the columns in your model's definition.
  
  | column_name  | definition_type | contract_type | mismatch_reason     |
  | ------------ | --------------- | ------------- | ------------------- |
  | created_date | DATE            |               | missing in contract |
```
```


### Environment

```markdown
- OS: dbt-cloud (through dbt Cloud CLI 0.38.18)
- Python: 3.12
- dbt-core: 1.9 (latest)
- dbt-bigquery: 1.9.0
```

**Comment by madamak** [comment]
Hi @amychen1776, I have the exact same issue as @LennartKloppenburg. Here is my setup, I am on version 1.8.0:

```sql 
-- model.sql
config(
    materialized='incremental',
    incremental_strategy = 'insert_overwrite',
    partition_by={
      "field": "timestamp",
      "data_type": "timestamp",
      "granularity": "hour",
      "time_ingestion_partitioning": true,
      "copy_partitions": true
    }

{% ... %}

final AS (
    SELECT
        timestamp,
        logs
    FROM table
)

SELECT * FROM final 
```

```yml 
# model.yml
name: model
    config:
      access: public
      contract:
        enforced: true
    columns:
      - name: timestamp
        data_type: TIMESTAMP
      - name: log # (and other struct fields)
        data_type: STRUCT
```

With the above setup, dbt generates an `INSERT` statement that expects 3 columns (due to the contract and `_PARTITIONTIME`): `_PARTITIONTIME`, `timestamp`, `log`.

However, the `SELECT` statement generated by dbt is approximately `SELECT TIMESTAMP(timestamp) AS _PARTITIONTIME, * EXCEPT(timestamp) FROM` .... This `SELECT` only produces 2 columns: `_PARTITIONTIME` and `log` (because `timestamp` is used in `partition_by.field` and then excluded).
This results in a "Query error: Inserted row has wrong column count; Has 2, expected 3".

I have tried several workarounds:
1. Adding a _sacrificial_ column `_dbt_partition_source_ts`

That would be just a duplicate of `timestamp` in the final SQL statement and changing the `partition_by.field` to `_dbt_partition_source_ts`

This results in:
```
  This model has an enforced contract that failed.
  Please ensure the name, data_type, and number of columns in your contract match the columns in your model's definition.
  
  | column_name              | definition_type | contract_type | mismatch_reason     |
  | ------------------------ | --------------- | ------------- | ------------------- |
  | _dbt_partition_source_ts | TIMESTAMP       |               | missing in contract |
```

2. If add this column to the yml file I then get the error that the select produces 3 columns and that 4 are expected.

Can you please help?
