### ISSUE TITLE
[Feature] Support the updating of incremental model description after initial creation

### ISSUE THREAD

**Issue by kiwamizamurai** [dbt-labs/dbt-adapters#585]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Table description does not changed even thought I modify the `schema.yml` with `persist_docs=true` and `materialized=incremental`.

### Expected Behavior

Table description should be altered regardless of materialization type.

### Steps To Reproduce

1. write the hogehoge.sql as follows

```sample.sql
{{
  config(
    materialized = 'incremental',
    persist_docs = {"relation": true, "columns": true}
  )
}}

select 1 as first_col
from unnest([struct(1 as dual)]) as dual

{% if is_incremental() %}
    where 1=1
{% endif %}
```

2. write the hogehoge.yaml as follows

```yaml
version: 2

models:
  - name: hogehoge
    description: before_changed
    columns:
      - name: first_col
        description: before_changed
```

3. run the command `dbt build --select hogehoge`
4. confirm that the table is created in bigquery console
5. modify the sample.yaml as follows

```yaml
version: 2

models:
  - name: hogehoge
    description: after_changed
    columns:
      - name: first_col
        description: after_changed
```

6. confirm that only the column description is updated

### Relevant log output

```bash
08:36:20  Concurrency: 4 threads (target='dev')
08:36:20  
08:36:20  1 of 1 START sql table model dbt_some_project.hogehoge ...................... [RUN]
08:36:24  1 of 1 OK created sql table model dbt_some_project.hogehoge ................. [CREATE TABLE (1.0 rows, 0 processed) in 4.13s]
08:36:24  
08:36:24  Finished running 1 table model in 0 hours 0 minutes and 9.00 seconds (9.00s).
08:36:24  
08:36:24  Completed successfully
```

### Environment

```markdown
- OS: MacOS13.6
- Python: 3.11.7
- dbt-core: 1.7.6
- dbt-bigquery: 1.7.6
```

### Additional Context

I have not observed this phenomenon with other data platform adapter like snowflake.
