### ISSUE TITLE
[Feature] Change BigQuery `labels` to be additive instead of "clobber"

### ISSUE THREAD

**Issue by moseleyi** [dbt-labs/dbt-adapters#587]
### Current Behavior

When we set labels in `dbt_project.yml`
```
      finance: 
        +labels:
          domain: finance
          test: "yes"
```

and then extra ones in the model file

```
{{
  config(
    labels = {"type": "financial", "contains_pii": "yes"}
  )
}}
```

The configuration of the model gets overwritten, even though the labels are different.

![image](https://github.com/dbt-labs/dbt-bigquery/assets/16131590/addb27af-529f-4dc9-8067-45e93fcbead8)

### Expected Behavior

I expected all labels to be applied and if a label is specified twice then for the single model configuration to take precedence.

### Steps To Reproduce

Create a sample model in folder `models/finance/finance_test.sql` and add the following configuration:

```
{{
  config(
    labels = {"type": "financial", "contains_pii": "yes"}
  )
}}
```

In `dbt_project.yml` add the following configuration:

```
models:
  project_name:
    finance:
      +labels:
        domain: finance
        test: yes
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.8.4rc1
- dbt: 1.7.7
- dbt-bigquery: 1.7.4
```
