### ISSUE TITLE
Default test name causes compilation error with `--store-failures` flag

### ISSUE THREAD

**Issue by ClauPet** [dbt-labs/dbt-adapters#625]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have the following dbt model:

test.sql

 ```
 column_name | val
-------------+-----
 A           | 0.4
 B           | 0.4
```

test.yml

```
models:
  - name: test
    columns:
      - name: column_name
        tests:
          - accepted_values:
              values: ['A', 'B', 'C'] 
```

After creating the model, I run the test doing `dbt test --select test --store_failures`. An empty table named `accepted_values_test_column_name__a__b__c` is created in the `dbt_test__audit` schema of my Redshift database. The second time I run the exact same command I get a compilation error saying that there is not table `accepted_values_test_column_name__A__B__C`.

Redshift by default uses case insensitive identifiers, e.g. table names. I know I could get around this by adding a custom lower case test names. However, this is not desirable with the amount of accepted values tests I have. 

### Expected Behavior

I would expect dbt to know of the case insensitivity of Redshift identifiers and not try to crate a table `accepted_values_test_column_name__A__B__C`.

### Steps To Reproduce

1. Create an accepted values test with capital test values
2. run `dbt test --store-failures` twice 

### Relevant log output

```shell
Compilation Error in test accepted_values_test_column_name__A__B__C (models/master_data/test.yml)
  When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete "reddw"."dbt_test__audit"."accepted_values_test_column_name__a__b__c", or rename it to be less ambiguous.
  Searched for: "reddw"."dbt_test__audit"."accepted_values_test_column_name__A__B__C"
  Found: "reddw"."dbt_test__audit"."accepted_values_test_column_name__a__b__c"
```

### Environment

```markdown
- Python:3.10.2
- dbt-core:1.7.11
- dbt-redshift: 1.7.5
```

### Which database adapter are you using with dbt?

redshift

**Comment by dbeatty10** [comment]
I believe the root cause here is the default `enable_case_sensitive_identifier=false` setting in Redshift -- it's really unfortunate behavior IMO!

For anyone that can't or doesn't want to upgrade to `enable_case_sensitive_identifier=true`, we have an easy and reasonable workaround by using a [custom name for this data test](https://docs.getdbt.com/reference/resource-properties/data-tests#custom-data-test-name), so I'm going to close this as not planned.

Example:

```yaml
models:
  - name: test
    columns:
      - name: column_name
        tests:
          - accepted_values:
              # Give the data test a custom name that is all lowercase
              name: test_name_all_lowercase
              values: ['A', 'B', 'C'] 
```
