### ISSUE TITLE
[ADAP-474] [Feature] Accept users, groups, or roles in grants config on resource

### ISSUE THREAD

**Issue by stevenayers-tvx** [dbt-labs/dbt-adapters#647]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After specifically creating the group `finance_department` in Redshift, I cannot use it as a grantee in the grant config.

I can see the group when I run `SELECT * FROM pg_group`

```yaml
models:
  - name: specific_model
    config:
      grants:
        select: ['finance_department']
```

Error: `user "finance_department" does not exist`

### Expected Behavior

Grantee syntax says groups, not just users, should be accepted: https://docs.getdbt.com/reference/resource-configs/grants#common-syntax

### Steps To Reproduce

1. Create a group in redshift
2. Add to a grants config on a model

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-redshift:
```
