### ISSUE TITLE
[ADAP-383] [Feature] Support Dynamic Data Masking in CTAS Statements

### ISSUE THREAD

**Issue by jdoldis** [dbt-labs/dbt-adapters#85]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently you cannot specify [column masking policies](https://docs.snowflake.com/en/user-guide/security-column-ddm-intro#what-is-dynamic-data-masking) in Snowflake `CTAS` statements with dbt-snowflake. For example, `CREATE TABLE <table_name>(<col_name> <col_type> WITH MASKING POLICY <policy_name>) AS SELECT <query>`.

As a workaround masking policies can be applied to columns in a dbt post hook using an `ALTER TABLE` statement. The issue with doing this is that the `CTAS` and `ALTER TABLE` statements cannot be issued in the same transaction, as per the [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/transactions#ddl) - "Each DDL statement executes as a separate transaction". As a result there is there is a small window of time between the `CTAS` and `ALTER TABLE <table_name> MODIFY COLUMN <column_name> SET MASKING POLICY <policy_name>` statements where the data is not masked, and if the `ALTER TABLE` statement fails it would remain that way.

Supporting masking policy specification in the CTAS statement would fix this. As per the [Snowflake documentation](https://docs.snowflake.com/en/user-guide/security-column-intro#create-table-as-select-ctas-statements) "Executing a CREATE TABLE … AS SELECT (CTAS) statement applies any masking policies on columns included in the statement before the data is populated in the new table".

It also may not be difficult to support this given the recent work on [model contracts ](https://github.com/dbt-labs/dbt-core/discussions/6726) which provides the `CREATE TABLE <table_name>(<col_name> <col_type>) AS SELECT <query>` syntax. All that would need to be added is the `WITH MASKING POLICY <policy_name>` part of the statement.

One way to provide the config would be something like:

```
columns:
      - name: id
        description: "Primary key for this model"
        data_type: integer
        masking_policy: <policy_name>
        contraints: <constraint_list>
        ...
```

The masking policy could then be applied in [get_columns_spec_ddl](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/utils/get_columns_spec_ddl.sql).

### Describe alternatives you've considered

Using an `ALTER TABLE` statement in a post hook to apply the masking policy. As described above due to Snowflake DDL statements always being executed in separate transactions this leaves the possibility of unmasked data.

### Who will this benefit?

Anyone that wants to take advantage of dynamic data masking in Snowflake using dbt.

### Are you interested in contributing this feature?

Yes

**Comment by jdoldis** [comment]
I still think this would be a great security improvement for DBT, commenting to keep the issue open.

**Comment by b-per** [comment]
Today with contracts and constraints, we actually support tag-based masking policies with the follwing syntax

```
models:
  - name: my_model
    config:
      contract: {enforced: true}
      materialized: table
    columns:
      - name: id
        data_type: int
        constraints:
          - type: custom
            expression: "tag (my_tag = 'my_value')"
```

This requires defining all the columns and their types though.

Would it work for your use case?

**Comment by jdoldis** [comment]
That's great news, hadn't realised that, thanks @b-per ! I don't currently have all column types documented, but I can move to that 👍

**Comment by jellerbee-altr** [comment]
@b-per This seems promising but is there any documentation on custom constraints?  In particular docs on the expression "tag (my_tag = 'my_value')"

**Comment by jellerbee-altr** [comment]
Okay I figured it out.  The expression is simply the SQL to represent the constraint on the column.

**Comment by grantith** [comment]
@b-per That's interesting, I didn't know that was possible! I'll have to give it a shot. If only I had a good way to add row access policies in snowflake, too.

@jdoldis You might find something like [dbt-osmosis](https://github.com/z3z1ma/dbt-osmosis) useful for quickly generating model docs.

**Comment by b-per** [comment]
Also, I have not tried it, but I think that you could add directly a masking policy instead of using tags

```
models:
  - name: my_model
    config:
      contract: {enforced: true}
      materialized: table
    columns:
      - name: id
        data_type: int
        constraints:
          - type: custom
            expression: "masking policy my_policy"
```
