### ISSUE TITLE
[BUG] Snapshot YAML Config does not work on calculated column expressions

### ISSUE THREAD

**Issue by ataft** [dbt-labs/dbt-adapters#903]
dbt version: 1.9.2
Database: Redshift

The following snapshot YAML configuration does not work:
``` yaml
  - name: snapshot__sometable
    relation: source('somesource', 'sometable')
    config:
      enabled: true
      unique_key: ["unique_id"]
      strategy: timestamp
      updated_at: "(CAST(TO_CHAR(CREATE_DATE, 'YYYY-MM-DD') || ' ' || TO_CHAR(CREATE_TIME, 'HH24:MI:SS') as timestamp))"
```

I believe that the only reason is due to this line, which sets the `row_changed` variable:
https://github.com/dbt-labs/dbt-adapters/blob/34fd178539dcb6f82e18e738adc03de7784c032f/dbt-adapters/src/dbt/include/global_project/macros/materializations/snapshots/strategies.sql#L71

The error is because the where clause is trying to reference a `table.column`, which will not work for calculated columns. However, the calculated column is already set in the `source_data` CTE, so it could simply reference that column and work.

For verification that this is not a BREAKING change, it appears that the `row_changed` variable is only used in two places:

1. https://github.com/dbt-labs/dbt-adapters/blob/34fd178539dcb6f82e18e738adc03de7784c032f/dbt-adapters/src/dbt/include/global_project/macros/materializations/snapshots/helpers.sql#L112
2. https://github.com/dbt-labs/dbt-adapters/blob/34fd178539dcb6f82e18e738adc03de7784c032f/dbt-adapters/src/dbt/include/global_project/macros/materializations/snapshots/helpers.sql#L132

Updating the `row_changed` logic to the following works for me:
```
    {% set row_changed_expr -%}
        ({{ snapshotted_rel }}.{{ columns.dbt_valid_from }} < {{ current_rel }}.{{ columns.dbt_valid_from }})
    {%- endset %}
```

This will resolve to something like `snapshotted_data.dbt_valid_from < source_data.dbt_valid_from`. You can see that the source_data.dbt_valid_from column is the `updated_at` expression.

Am I missing anything? If not, I'm happy to make a PR.
